import 'package:flutter/material.dart';

/* Text 12:00 - 12:30 PM
    Autogenerated by FlutLab FTF Generator
  */
class Generated12001230PMWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''12:00 - 12:30 PM''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
